### ISSUE TITLE
Invalid peer dependency

### ISSUE THREAD

**Issue by jsifalda** [Byteclaw/hooks#16]
Hey there,

https://github.com/Byteclaw/hooks/blob/master/packages/use-unique-id/package.json

uses @types/react as peer dep, although i believe it was supposed to be in dev deps? 
It is hard to use this package with react 17 atm..

thanks in advance.

**Comment by michalkvasnicak** [comment]
Hey!

No it's supposed to be in peer dependencies because I don't want this library to download specific version and cause collisions.

What is the problem with it?

**Comment by jsifalda** [comment]
I see. Hmm, the problem is that in this setup, we are not able to use this lib together with react 17, unless we force install it. 
At first glance, the this lib works just fine with react v17, and therefore the question is, does it need to be locked to @types/react^16.9.11 when you allow to use react v17? 🤔  (based on what you have in package.json file)

**Comment by michalkvasnicak** [comment]
Ah I see. During the time when the last version of this lib has been published there was no production ready React 17 so there weren't any types for it. I will fix the peer dependency version signature.

**Comment by jsifalda** [comment]
thx

**Comment by michalkvasnicak** [comment]
Released as `1.0.2`
